/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "dot1dBridge.h"
#include "dot1dBridge_scalars.h"

/** Initializes the dot1dBridge module */
void
init_dot1dBridge_scalars(void)
{
    const oid dot1dBaseBridgeAddress_oid[] = { 1,3,6,1,2,1,17,1,1 };
    const oid dot1dBaseNumPorts_oid[] = { 1,3,6,1,2,1,17,1,2 };
    const oid dot1dBaseType_oid[] = { 1,3,6,1,2,1,17,1,3 };
    const oid dot1dStpProtocolSpecification_oid[] = { 1,3,6,1,2,1,17,2,1 };
    const oid dot1dStpPriority_oid[] = { 1,3,6,1,2,1,17,2,2 };
    const oid dot1dStpTimeSinceTopologyChange_oid[] = { 1,3,6,1,2,1,17,2,3 };
    const oid dot1dStpTopChanges_oid[] = { 1,3,6,1,2,1,17,2,4 };
    const oid dot1dStpDesignatedRoot_oid[] = { 1,3,6,1,2,1,17,2,5 };
    const oid dot1dStpRootCost_oid[] = { 1,3,6,1,2,1,17,2,6 };
    const oid dot1dStpRootPort_oid[] = { 1,3,6,1,2,1,17,2,7 };
    const oid dot1dStpMaxAge_oid[] = { 1,3,6,1,2,1,17,2,8 };
    const oid dot1dStpHelloTime_oid[] = { 1,3,6,1,2,1,17,2,9 };
    const oid dot1dStpHoldTime_oid[] = { 1,3,6,1,2,1,17,2,10 };
    const oid dot1dStpForwardDelay_oid[] = { 1,3,6,1,2,1,17,2,11 };
    const oid dot1dStpBridgeMaxAge_oid[] = { 1,3,6,1,2,1,17,2,12 };
    const oid dot1dStpBridgeHelloTime_oid[] = { 1,3,6,1,2,1,17,2,13 };
    const oid dot1dStpBridgeForwardDelay_oid[] = { 1,3,6,1,2,1,17,2,14 };
    const oid dot1dTpLearnedEntryDiscards_oid[] = { 1,3,6,1,2,1,17,4,1 };
    const oid dot1dTpAgingTime_oid[] = { 1,3,6,1,2,1,17,4,2 };

  DEBUGMSGTL(("dot1dBridge_scalars", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dBaseBridgeAddress", handle_dot1dBaseBridgeAddress,
                               dot1dBaseBridgeAddress_oid, OID_LENGTH(dot1dBaseBridgeAddress_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dBaseNumPorts", handle_dot1dBaseNumPorts,
                               dot1dBaseNumPorts_oid, OID_LENGTH(dot1dBaseNumPorts_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dBaseType", handle_dot1dBaseType,
                               dot1dBaseType_oid, OID_LENGTH(dot1dBaseType_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpProtocolSpecification", handle_dot1dStpProtocolSpecification,
                               dot1dStpProtocolSpecification_oid, OID_LENGTH(dot1dStpProtocolSpecification_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpPriority", handle_dot1dStpPriority,
                               dot1dStpPriority_oid, OID_LENGTH(dot1dStpPriority_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpTimeSinceTopologyChange", handle_dot1dStpTimeSinceTopologyChange,
                               dot1dStpTimeSinceTopologyChange_oid, OID_LENGTH(dot1dStpTimeSinceTopologyChange_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpTopChanges", handle_dot1dStpTopChanges,
                               dot1dStpTopChanges_oid, OID_LENGTH(dot1dStpTopChanges_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpDesignatedRoot", handle_dot1dStpDesignatedRoot,
                               dot1dStpDesignatedRoot_oid, OID_LENGTH(dot1dStpDesignatedRoot_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpRootCost", handle_dot1dStpRootCost,
                               dot1dStpRootCost_oid, OID_LENGTH(dot1dStpRootCost_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpRootPort", handle_dot1dStpRootPort,
                               dot1dStpRootPort_oid, OID_LENGTH(dot1dStpRootPort_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpMaxAge", handle_dot1dStpMaxAge,
                               dot1dStpMaxAge_oid, OID_LENGTH(dot1dStpMaxAge_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpHelloTime", handle_dot1dStpHelloTime,
                               dot1dStpHelloTime_oid, OID_LENGTH(dot1dStpHelloTime_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpHoldTime", handle_dot1dStpHoldTime,
                               dot1dStpHoldTime_oid, OID_LENGTH(dot1dStpHoldTime_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpForwardDelay", handle_dot1dStpForwardDelay,
                               dot1dStpForwardDelay_oid, OID_LENGTH(dot1dStpForwardDelay_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpBridgeMaxAge", handle_dot1dStpBridgeMaxAge,
                               dot1dStpBridgeMaxAge_oid, OID_LENGTH(dot1dStpBridgeMaxAge_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpBridgeHelloTime", handle_dot1dStpBridgeHelloTime,
                               dot1dStpBridgeHelloTime_oid, OID_LENGTH(dot1dStpBridgeHelloTime_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dStpBridgeForwardDelay", handle_dot1dStpBridgeForwardDelay,
                               dot1dStpBridgeForwardDelay_oid, OID_LENGTH(dot1dStpBridgeForwardDelay_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dTpLearnedEntryDiscards", handle_dot1dTpLearnedEntryDiscards,
                               dot1dTpLearnedEntryDiscards_oid, OID_LENGTH(dot1dTpLearnedEntryDiscards_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("dot1dTpAgingTime", handle_dot1dTpAgingTime,
                               dot1dTpAgingTime_oid, OID_LENGTH(dot1dTpAgingTime_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_dot1dBaseBridgeAddress(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_char *value;
    size_t  varlen;

    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_BaseBridgeAddress_get(bridge_name, &value, &varlen)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, value, varlen);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dBaseBridgeAddress\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_dot1dBaseNumPorts(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;

    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_BaseNumPorts_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            }
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dBaseNumPorts\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_dot1dBaseType(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    u_long value = 2;           /* transparent-only */
    switch(reqinfo->mode) {

        case MODE_GET:
            if (bridge_name) {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            } else {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            }
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dBaseType\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_dot1dStpProtocolSpecification(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    u_long value = 3;           /* ieee8021d */

    switch(reqinfo->mode) {

        case MODE_GET:
            if (bridge_name) {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            } else {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            }
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpProtocolSpecification\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_dot1dStpPriority(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;

    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpPriority_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpPriority\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_dot1dStpTimeSinceTopologyChange(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpTimeSinceTopologyChange_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                value *= 100;
                snmp_set_var_typed_value(requests->requestvb, ASN_TIMETICKS,
                                         (u_char *)&value, sizeof(value));
            }
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpTimeSinceTopologyChange\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_dot1dStpTopChanges(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpTopChanges_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_COUNTER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpTopChanges\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_dot1dStpDesignatedRoot(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_char *value;
    size_t  varlen;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpDesignatedRoot_get(bridge_name, &value, &varlen)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, value, varlen);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpDesignatedRoot\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_dot1dStpRootCost(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpRootCost_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpRootCost\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_dot1dStpRootPort(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpRootPort_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpRootPort\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_dot1dStpMaxAge(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpMaxAge_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpMaxAge\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_dot1dStpHelloTime(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpHelloTime_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpHelloTime\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_dot1dStpHoldTime(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpHoldTime_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpHoldTime\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_dot1dStpForwardDelay(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpForwardDelay_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpForwardDelay\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_dot1dStpBridgeMaxAge(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpBridgeMaxAge_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpBridgeMaxAge\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_dot1dStpBridgeHelloTime(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpBridgeHelloTime_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpBridgeHelloTime\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_dot1dStpBridgeForwardDelay(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_StpBridgeForwardDelay_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dStpBridgeForwardDelay\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_dot1dTpLearnedEntryDiscards(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_TpLearnedEntryDiscards_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_COUNTER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dTpLearnedEntryDiscards\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_dot1dTpAgingTime(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int rc;
    u_long value;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            if (!bridge_name ||
                (rc = netsnmp_arch_bridge_scalars_TpAgingTime_get(bridge_name, &value)) != 0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_NOSUCHINSTANCE);
            } else {
                snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                         (u_char *)&value, sizeof(value));
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dTpAgingTime\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
