/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef DOT1DTPPORTTABLE_OIDS_H
#define DOT1DTPPORTTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table dot1dTpPortTable */
#define DOT1DTPPORTTABLE_OID              1,3,6,1,2,1,17,4,4


#define COLUMN_DOT1DTPPORT         1
#define COLUMN_DOT1DTPPORT_FLAG    (0x1 << 0)
    
#define COLUMN_DOT1DTPPORTMAXINFO         2
#define COLUMN_DOT1DTPPORTMAXINFO_FLAG    (0x1 << 1)
    
#define COLUMN_DOT1DTPPORTINFRAMES         3
#define COLUMN_DOT1DTPPORTINFRAMES_FLAG    (0x1 << 2)
    
#define COLUMN_DOT1DTPPORTOUTFRAMES         4
#define COLUMN_DOT1DTPPORTOUTFRAMES_FLAG    (0x1 << 3)
    
#define COLUMN_DOT1DTPPORTINDISCARDS         5
#define COLUMN_DOT1DTPPORTINDISCARDS_FLAG    (0x1 << 4)
    

#define DOT1DTPPORTTABLE_MIN_COL   COLUMN_DOT1DTPPORT
#define DOT1DTPPORTTABLE_MAX_COL   COLUMN_DOT1DTPPORTINDISCARDS
    


#ifdef __cplusplus
}
#endif

#endif /* DOT1DTPPORTTABLE_OIDS_H */
